### ISSUE TITLE
Fix thumbnail left alignment

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#323]
**Describe the bug**
Left thumbnail alignment does not affect embeds. As a result, thumbnails on the feed bounce left and right depending on the post type, which is somewhat annoying.

Edit: More left align issues

**To Reproduce** (if applicable)
- Set thumbnail alignment to left
- Browse in list view

Tasks:
- [x] (list view) - Apply thumbnail alignment to embeds. ~~#344~~ 80fff16671b9e519148456eaa7c96cb545072115
- [x] (list view) - Consistent horizontal position of meta block. #353 
- [x] (compact view) - Consistent horizontal position of meta block. #340 
- [x] Alt text is obscured by the left sidebar. 6c047be49d3f8bda9de81fd083c4716864274f43

**Expected behavior**
Consistent thumbnail position on both alignment options.

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/100710152/a230cd50-f82d-4885-b9e6-276e00b7eb67)

**Versions**
- Browser: Firefox
- Photon version: 1.29.5

**Comment by sevonj** [comment]
I spent some more time thinking about ways to make left alignment look cleaner.

I don't like these paths at all:
![image](https://github.com/Xyphyn/photon/assets/100710152/04c5f918-615e-4169-980d-558b1a34f18d)

The best idea I have so far is this:
![image](https://github.com/Xyphyn/photon/assets/100710152/d76d9916-59b9-43f2-b574-7d1f7efd10d2)

- Use normal "media" item for embed thumbnails when leftAlign is on.
- Reserve the space even if there is no media when leftAlign is on.
  - Maybe put some kind of text post symbol there.
- Change the layout so that embed comes after media.

Title and meta moved above in list view:
![image](https://github.com/Xyphyn/photon/assets/100710152/5ba877f9-3e2a-404a-972f-d2e152763a49)

Compact mode:
![image](https://github.com/Xyphyn/photon/assets/100710152/5abca95d-2cd3-41e3-a2e6-0fad0d77e150)

@Xyphyn Opinion on having roughly this kind of layout for leftAlign?

**Comment by Xyphyn** [comment]
Sure I completely forgot about left alignment

**Comment by sevonj** [comment]
I rebuilt that draft and pushed it to https://github.com/sevonj/photon/tree/left_align

It's rough, but I think the the layout idea is ok.

Changed views:
- list (left align)
- compact (left align)
- compact (right align)

<details>
<summary>Screenshots</summary>

List left
![image](https://github.com/Xyphyn/photon/assets/100710152/9aee837f-850e-4992-8194-12d6b585d877)

Compact left
![image](https://github.com/Xyphyn/photon/assets/100710152/9929f6c9-13c0-4724-a07b-ab888d64b083)

Compact right
![image](https://github.com/Xyphyn/photon/assets/100710152/969d8d46-9a22-42ce-8d90-d92397f53e73)

</details>

**Comment by sevonj** [comment]
I wasn't really happy with my previous draft for list view. Left and right alignments had different layouts and it looked kinda weird anyway.

So I had another go:
My new approach doesn't try to bend the embed thumbnails to match the normal ones. They stay in the embed card. Instead, I made the normal layout more consistent with embeds by moving the meta block above.

![image](https://github.com/Xyphyn/photon/assets/100710152/6afc1dd2-0d27-4d24-854f-7bd9a99336d8)

We could also increase the size a bit, maybe even match the width of the embed thumbnail.

![image](https://github.com/Xyphyn/photon/assets/100710152/a09adb76-c8da-4903-b5ec-264e2f94cb66)

![image](https://github.com/Xyphyn/photon/assets/100710152/27b60301-32f3-4519-ac63-7916919b7fe9)

**Comment by sevonj** [comment]
I guess I'll add alt text to the list.

![image](https://github.com/Xyphyn/photon/assets/100710152/af52e1d8-7696-41b1-9352-1f1ad6e57248)

**Comment by sevonj** [comment]
I see that list view layout has become near identical to compact layout.
![image](https://github.com/Xyphyn/photon/assets/100710152/9a247c41-d37b-4293-9e30-7e91e366b790)

At this point, instead of working a new solution, I suggest just removing the filter for selfposts in PostMediaCompact to make it consistent.

https://github.com/Xyphyn/photon/blob/80fff16671b9e519148456eaa7c96cb545072115/src/lib/components/lemmy/post/media/PostMediaCompact.svelte#L20C1-L20C3

**Comment by sevonj** [comment]
Looks like we're done here!
