### ISSUE TITLE
UI doesn't fit on narrow screens.

### ISSUE THREAD

**Issue by sevonj** [Xyphyn/photon#342]
**Describe the bug**
My phone reports its screen width as 360 px. Photon does not like screens this narrow.

- [x] Post meta wraps #347
- [x] Post badges overflow 
- [x] The dock overflows.
- [x] Thin embed thumbnails (or leave as is?) #360 
- [ ] Something in the UI is too wide for 360 px. #365 

**To Reproduce** (if applicable)
- Open responsive design view in firefox (ctrl+shift+m) and set width.

**Expected behavior**
 \- 

**Screenshots**
![image](https://github.com/Xyphyn/photon/assets/100710152/628e8bfe-e173-4001-ae83-0ae0c7627464)

**Versions**
- Browser: Firefox
- Photon version: 1.30.3 (main)
  - check in the bottom of the main menu.

**Comment by Xyphyn** [comment]
View select box is supposed to not be visible on mobile, and the posts seem to be displaying correctly.

I'll fix the navbar though.

**Comment by sevonj** [comment]
> View select box is supposed to not be visible on mobile

Oh.

Should've been more specic for the posts. Meta wraps around like this. I didn't catch it while browsing for examples now, but it looks real janky when it wraps in multiple places at the same time.

![20240624_224718.jpg](https://github.com/Xyphyn/photon/assets/100710152/17b1d228-5aa1-4dc4-8d62-344c8c752d49)

![20240624_224744.jpg](https://github.com/Xyphyn/photon/assets/100710152/c221b68b-f404-438c-ac1e-51125f556919)

(And this place again)
![20240624_224803.jpg](https://github.com/Xyphyn/photon/assets/100710152/395aa5dc-191b-4d20-9ede-e7ca713b918f)


A small thing, embed thumbnails can get even thinner than this.

![20240624_224824.jpg](https://github.com/Xyphyn/photon/assets/100710152/ef8c6049-4668-44d2-9c0a-19a1cc03f90e)

**Comment by Xyphyn** [comment]
I'm not sure how I'd wrap this. Maybe I could just hide the instance url at small enough sizes.

**Comment by sevonj** [comment]
Overflow ellipsis for both user and community?

**Comment by sevonj** [comment]
I enabled some badges. 
![image](https://github.com/Xyphyn/photon/assets/100710152/b6d93279-089b-4294-8fdb-70ade9ebbb04)

**Comment by Xyphyn** [comment]
Uh oh. I'll get on this soon

**Comment by sevonj** [comment]
So, I think this can be fixed with two changes that are probably annoying to build.

- Make meta not wrap and use overflow-ellipsis for user & community. ![image](https://github.com/Xyphyn/photon/assets/100710152/54996ed0-e0df-4687-ab50-1dcd95987f7e) https://github.com/sevonj/photon/tree/meta-ellipsis-draft

- Move badges div below if screen width is small.
![image](https://github.com/Xyphyn/photon/assets/100710152/fbca2c15-db1c-4d8d-98b5-06f40562c445)
And maybe the badges smaller there, too.

**Comment by Xyphyn** [comment]
CSS flexbox's default overflow rules are stupid as fuck, why do the most random things shrink except the ones i explicitly tell to shrink???? mix that with css grid and your layout is a living hell now

**Comment by sevonj** [comment]
> CSS flexbox's default overflow rules are stupid as fuck, why do the most random things shrink except the ones i explicitly tell to shrink???? mix that with css grid and my layout is a living hell now

I know, right

I see the dock overflow is fixed. Is the menu button supposed to shrink?
![image](https://github.com/Xyphyn/photon/assets/100710152/49dd7be8-9080-4bbf-a6d8-305a0cddd7e2)

Meta is janky but at least it doesn't overflow.
![image](https://github.com/Xyphyn/photon/assets/100710152/65f5c0dd-9305-4d72-b587-db53a5d7fc90)
![image](https://github.com/Xyphyn/photon/assets/100710152/a1b09216-8d05-4ab2-80fc-ba63c22bc35b)
![image](https://github.com/Xyphyn/photon/assets/100710152/9f07efad-1235-41ac-90a1-d96e3e9bf12f)

I'll check these two boxes.

**Comment by Xyphyn** [comment]
All tasks completed, reopen this issue if there's anything more needed to be done.

**Comment by sevonj** [comment]
> All tasks completed, reopen this issue if there's anything more needed to be done.

Well it happened rather soon.

![image](https://github.com/user-attachments/assets/13b2a147-dd3f-4fee-aab7-e51a55d2a8f4)
![image](https://github.com/user-attachments/assets/1c089a11-3d93-4e14-8830-6f4d07cfb5b2)
